name: Container

on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:12-alpine
    steps:
      - name: log node version
        run: node -v
      - name: step with docker
        uses: docker://node:14-alpine
        with:
          entrypoint: '/bin/echo'
          args: 'Hello World'
      - name: log node version
        uses: docker://node:14-alpine
        with:
          entrypoint: '/usr/local/bin/node'
          args: -v
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: cjay91/node-app
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Post a user
        run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username":"hello","address":"dwded"}'''
      - name: Fetch Users
        run: curl http://localhost:3001/api/users
